name: Run checks
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  - push
  - workflow_dispatch
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - run: luacheck .          
